defaults:
  - classcond_deferred_dit_imagenet256_latent_m2_moe_schema

_target_: models_dit.ClassCondDeferredMaskingDiT
_recursive_: true
in_ch: 4
latent_size: 32
patch_size: 2
num_classes: 1000
patch_mixer:
  _target_: models_dit.PatchMixer
  hidden_size: 768
  use_gradient_checkpointing: ${..use_gradient_checkpointing}
  blocks:
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 12
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 3072
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 12
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1536
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
masker:
  _target_: models_dit.RandomTokenMasker
  mask_ratio: 0.75
backbone:
  _target_: models_dit.DiTBackbone
  hidden_size: 1024
  use_gradient_checkpointing: ${..use_gradient_checkpointing}
  blocks:
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 512
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 512
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 576
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 352
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 576
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 896
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 640
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 544
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 640
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1280
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 704
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 736
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 704
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1664
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 704
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 928
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 768
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 2048
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 768
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1120
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 832
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 2432
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 832
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1312
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 896
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 2816
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 896
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1504
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 896
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 3200
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 960
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1696
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 960
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 3584
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 1024
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 1888
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 1024
    ffn:
      _target_: models_dit.DenseFFN
      hidden_size: ${..hidden_size}
      mlp_width: 3968
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
  - _target_: models_dit.DiTBlock
    hidden_size: ${...hidden_size}
    attention:
      _target_: models_dit.SelfAttention
      hidden_size: ${..hidden_size}
      num_heads: 16
      attention_width: 1024
    ffn:
      _target_: models_dit.PackedExpertChoiceMoEFFN
      hidden_size: ${..hidden_size}
      mlp_width: 2048
      num_experts: 16
      expert_capacity: 2.0
      activation:
        _target_: torch.nn.GELU
        approximate: tanh
time_dim: 768
class_dim: 768
pos_embedding:
  _target_: models_dit.RoPE2D
  base: 10000.0
use_gradient_checkpointing: false
