defaults:
  - vae_schema

_target_: vae.VAEWrapper
model_id: hustvl/vavae-imagenet256-f16d32-dinov2
backend: vavae
revision: null
subfolder: null
latent_shape: [32, 16, 16]
image_size: 256
scaling_factor: 1.0
torch_dtype: float32
sample_posterior: false
local_files_only: false
